# Generated by Django 5.2 on 2025-05-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_image_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_Decsription',
            new_name='decsription',
        ),
    ]
