# Generated by Django 5.2 on 2025-05-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0005_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
